services:
  - type: web
    name: docshield
    runtime: python
    nativePackages:
      - libzbar0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:flask_app
    envVars:
      - key: FLASK_ENV
        value: production
